name: Trigger auto deployment for stew-todo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/stew-todo-AutoDeployTrigger-d82e6788-d186-418b-af0f-99af44b3c9c5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.STEWTODO_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: stewmax.azurecr.io
          registryUsername: ${{ secrets.STEWTODO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STEWTODO_REGISTRY_PASSWORD }}
          containerAppName: stew-todo
          resourceGroup: Testing
          imageToBuild: stewmax.azurecr.io/stew-todo:${{ github.sha }}
          

     

